---
- name: Setup Calibre server using Docker
  hosts: myhosts
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: Install prerequisite Python packages for the Ansible module for Docker
      ansible.builtin.apt:
        name: python3-requests
    - name: Check if Docker is installed on system
      ansible.builtin.command: docker --version
      register: docker_valid
      changed_when: docker_valid.rc != 0
    - name: Setup Calibre container
      community.docker.docker_container:
        name: calibre-web-automated
        image: driftywinds/cwa:latest
        volumes:
          - /opt/calibre-web-automated/config/:/config
          - /opt/calibre-web-automated/book-ingest:/cwa-book-ingest
          - /mnt/synology/Calibre Library:/calibre-library # get books from nas
        restart_policy: unless-stopped
        ports:
          - 8083:8083
        env:
          TZ: Europe/Oslo
          PUID: "1000"
          PGID: "1000"
          DOCKER_MODS: "lscr.io/linuxserver/mods:universal-calibre-v7.16.0"
    - name: Check if NAS mount exists
      ansible.builtin.stat:
        path: /mnt/synology
      register: nas_mount
