- name: Firewall configuration using ufw
  hosts: myhosts
  become: true # Use this to specify you want to be root during the playbook!!!!
  tasks:
    - name: Accept OpenSSH-connections obviously duh
      community.general.ufw:
        rule: allow
        name: OpenSSH
    - name: Deny Censys IP addresses from accessing server
      community.general.ufw:
        rule: deny
        src: '{{ item }}'
        comment: 'Censys IP address'
      loop: "{{ lookup('file', 'extra/ips/banned_ip_ranges_censys.txt').splitlines() }}"
    - name: Deny specific Chinese IP addresses from accessing server
      community.general.ufw:
        rule: deny
        src: '{{ item }}'
        comment: 'Chinese/Alibaba IP address'
      loop: "{{ lookup('file', 'extra/ips/banned_ip_ranges_cn.txt').splitlines() }}"
