---
- name: Setup Navidrome server using Docker
  hosts: myhosts
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: Install prerequisite Python packages for the Ansible module for Docker
      ansible.builtin.apt:
        name: python3-requests
    - name: Check if Docker is installed on system
      ansible.builtin.command: docker --version
      register: docker_valid
      changed_when: docker_valid.rc != 0
    - name: Setup Navidrome container
      community.docker.docker_container:
        name: navidrome
        image: deluan/navidrome
        volumes:
          - /opt/navidrome/data:/data
          - /opt/navidrome/music:/music:ro
        restart_policy: unless-stopped
        user: 1000:1000
        ports:
          - 4533:4533
        env:
          ND_BASEURL: https://zel.stilk.tf 
