---
- name: Prune Docker
  hosts: myhosts
  become: true
  tasks:
    - name: Install prerequisite Python packages for the Ansible module for Docker
      ansible.builtin.apt:
        name: python3-requests
    - name: Check if Docker is installed on system
      ansible.builtin.command: docker --version
      register: docker_valid
      changed_when: docker_valid.rc != 0
    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
