- name: Reboot systems
  hosts: myhosts
  become: true

  tasks:
    - name: Remind user
      ansible.builtin.pause:
        prompt: "This will reboot every system in myhosts. Press Ctrl + C if you don't want to"
    - name: Reboot hosts
      ansible.builtin.reboot:
