- name: Update system
  hosts: myhosts
  become: true
  tasks:
    - name: Update repos and cache
      ansible.builtin.apt: 
        update_cache: true
        cache_valid_time: 3600
    - name: Upgrade apt packages
      ansible.builtin.apt:
        state: latest
        name: "*"
