name: ansible-lint
on: push 
jobs: 
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create vault_pass file
        env: 
          VAULT_PASS: ${{ secrets.VAULT_PASSWORD }}
        run: |
          touch .vault_pass
          echo $VAULT_PASS >> .vault_pass
        shell: bash
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
